"""
shell_integration.py — Shell hook mechanism (part of Module 1: Command Interceptor)

Ye module bash function definitions ko ek Python string ke roop me hold karta hai.
`safeshell shellinit` command ye poora script stdout pe print karta hai, jisse
tumhare .bashrc me ek line eval kar sake:

    eval "$(safeshell shellinit)"

Iske baad `safeshell-activate` aur `safeshell-down` functions har naye terminal
me automatically available honge — bilkul jaise `conda init` / `nvm` kaam karte hain.

IMPORTANT (why a Python script can't just do this itself):
Koi bhi child process (jaisa ki ek normal Python script chalne se banta hai)
apne PARENT SHELL ke environment ko modify nahi kar sakta — ye OS-level process
isolation hai (fork/exec model). Isi wajah se `rm`/`mv` ko override karna, ya
prompt (PS1) badalna, sirf isi tarah ho sakta hai: script khud print kare jo
karna hai, aur user apne shell me `eval`/`source` kare — script khud "run" nahi
ho sakta parent context me.
"""

SHELL_INIT_SCRIPT = r'''
# ── SafeShell shell integration (generated by `safeshell shellinit`) ──

safeshell-activate() {
    if [ -n "$_SAFESHELL_ACTIVE" ]; then
        echo "SafeShell is already active in this shell."
        return 0
    fi

    export _SAFESHELL_ACTIVE=1
    export _SAFESHELL_OLD_PS1="$PS1"

    rm()    { safeshell run "rm $*"; }
    mv()    { safeshell run "mv $*"; }
    chmod() { safeshell run "chmod $*"; }

    export PS1="(safeshell) $PS1"
    echo "SafeShell activated — rm, mv, and chmod are now intercepted in this shell."
    echo "Run 'safeshell-down' to deactivate."
}

safeshell-down() {
    if [ -z "$_SAFESHELL_ACTIVE" ]; then
        echo "SafeShell is not active in this shell."
        return 0
    fi

    unset -f rm mv chmod 2>/dev/null
    export PS1="$_SAFESHELL_OLD_PS1"
    unset _SAFESHELL_OLD_PS1
    unset _SAFESHELL_ACTIVE
    echo "SafeShell deactivated. rm/mv/chmod are back to normal."
}
'''


def get_shell_init_script() -> str:
    """Poora shell init script string ke roop me return karo (CLI ise print karega)."""
    return SHELL_INIT_SCRIPT
